### ISSUE TITLE
Pre and post-release checklist

### ISSUE THREAD

**Issue by cohenadair** [cohenadair/colour-tap#52]
This issue should always be kept open and in the in-progress state within a project as a reminder before release.

**Pre-Release**
- [x] Update in-app change log
- [x] Update version and build numbers
- [x] Update store description (Android)
- [x] Update store description (iOS) 
- [x] Update store screenshots (Android)
- [x] Update store screenshots (iOS)
- [x] Update website
- [x] Update privacy policy
  - Features that require internet section
- [x] Test changes in release build (Android)
- [x] Test changes in release build (iOS)
- [x] Test locale-specific changes (for example, strings)
- [x] Create social media image
- [x] Get next feature poll ready

**Post-Release**
- [x] Publish website changes
- [x] Social media post about new version
- [x] Update feature polls
- [x] Create GitHub release
